### PR TITLE
Autodesk Fusion compatibility

### PR DESCRIPTION
**Pull request by motla**
A quick patch to make the script work on Autodesk Fusion.

### CODE REVIEW

**Comment by yahyatawil** [comment]
Hi Romain, 

I've noticed that ULP is not working on Fusion, but did not have time to fix it. 

Let me try it on my end and accept the pull during next week. 

Thanks for the PR.

**Comment by motla** [comment]
Hi!
You're welcome! I noticed a crash today in a special case, I don't know exactly what causes it... I'm investigating...

**Comment by motla** [comment]
I had to simplify the script as the GROUP and DISPLAY commands seem broken in Fusion (I could not get them to work).

**Comment by yahyatawil** [comment]
@motla I've verfied it on my side. I confirm that `DISPLAY = mylayer LAST` are non-functional in Fusion. The `GROUP` command is working in the commad line, but I will check it from the ULP. I will add a check for the old ULP and the new one to instruct the user tp use the correct ULP version based on Eagle release. 

```
// For fusion it should be +9.7.x
int version = EAGLE_VERSION; // 9
int release = EAGLE_RELEASE; // 7

if(version == 9)
{
  if(release <= 7) // The last standalone version of EAGLE is 9.6.2
  {
    dlgMessageBox("This ULP is a ported version for Autodesk Fusion, For standalone Eagle use neg_silk.ulp instead","+OK");
  }
}
else if(version < 9) // Even older versions
{
    dlgMessageBox("This ULP is a ported version for Autodesk Fusion, For standalone Eagle use neg_silk.ulp instead","+OK");
}
```

Thanks

**Pull request merged**
